### ISSUE TITLE
Adapting extraction for depth

### ISSUE THREAD

**Issue by TranquilMarmot** [pink-arcana/godot-distance-field-outlines#10]
Hey! I love all the work that you've done on this.

I'm trying to adapt `extraction.glsl` to use depth instead of color, since I'm trying to reproduce the [effect from this shader](https://godotshaders.com/shader/high-quality-post-process-outline/) because it's causing me a lot of performance issues.

https://github.com/pink-arcana/godot-distance-field-outlines/blob/815fe196028cfb4c5d70dcb24d17bc074cf24c46/project/df_outline_ce/shaders/extraction.glsl#L90-L97

Do you have any advice for how to achieve this? It seems like `get_seed_depth` could maybe be repurposed to get the depth difference between one spot and its neighbors, but when I try that it still does the outline by color:

```
float depth = get_seed_depth(image_coord);
bool is_seed = depth > 0.5;
```

**Comment by pink-arcana** [comment]
That's interesting -- I've used that shader and it's beautiful. I never did profile it, though. Looking at it, I don't think it's doing anything more expensive than I am here, unless there's a loop I'm missing. But I'm curious now, so I'm going to try to copy/paste it in in a different branch and see what happens!

**Comment by TranquilMarmot** [comment]
After more experimentation, it looks like both methods (shader linked above using the "2x2 quad" trick, your method using compositing) do indeed have similar performance implications.

I think any sort of post-processing is _just_ enough to push Godot so that I can't get 60fps anymore 😢 I'm working on a 2020 M1 Macbook, so it's just using integrated graphics. I might try it out on my desktop with an RTX 2080 and see what happens there.

**Comment by pink-arcana** [comment]
Oh, that's too bad. I haven't been testing on enough hardware to have a good idea. Is your resolution high? Or is your scene already pretty heavy?

This was an interesting exercise, anyways! I put up my experiment in this branch: https://github.com/pink-arcana/godot-distance-field-outlines/blob/high-quality-pp-outline-embyr/project/df_outline_ce/shaders/extraction.glsl

This is a super naive implementation, though -- I'm not even sure I'm using the correct value for VIEW **(Edit: Can definitely confirm that the VIEW is INCORRECT in my shader.)**. I took out the outline width and distance fade calculations, since the extra passes in this project do that anyways, and changed the sampling to integer coords. (Integer coords are just how I already had it set up, you could do the fractional values by making an image sampler in the CompositorEffect).

I'm getting <1ms frame times on an RTX 3080 at 1080p. But with lots of artifacts. When I tried simple normals and depth sobels for outlines with this project earlier, I was getting some artifacts but not nearly this many, so there's probably some calculations I messed up or settings that should be changed (I just used the default uniform values).

Here's a gif (slowed way down):
![high_quality_pp_outlines_4](https://github.com/user-attachments/assets/88b74fbb-4ae1-4551-9cda-874afff35262)

**Comment by TranquilMarmot** [comment]
> Is your resolution high? Or is your scene already pretty heavy?

1920x1080, the scene itself is _pretty_ light. Performance is kind of all over the place when using post-processing like this, can't really nail it down to anything specific being rendered 🤷 Without any post-processing I get a solid 60fps no problem.

Thank you for the experiment! Very informative to see how you did it, I might try it out 👀

**Comment by pink-arcana** [comment]
It's interesting that shaders specifically seem to tank the performance. I know ARM chips have a lot of quirks and unsupported features (you may have seen this, but just in case: https://developer.arm.com/documentation/101897/0302). My big takeaway was that they don't support constant uniforms (so branching with uniforms is bad, even if all the pixels take the same branch) and their uniform storage is pretty limited. But neither my nor embyr's shader have branching (the branching in this project uses specialization constants, which should be ok with ARM). I wonder if there's some other gotcha there...

**Comment by pink-arcana** [comment]
Still haven't figured out a way to get correct value for VIEW in a CompositorEffect. I'm going to go ahead and close the branch so it doesn't mislead people into thinking it's working! :)
